# Generated by Django 3.2.5 on 2022-04-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_in_one_cp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='username',
        ),
    ]
