# Generated by Django 3.2.5 on 2022-04-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all_in_one_cp', '0002_delete_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='username',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='NA', max_length=100)),
            ],
        ),
    ]
