# Generated by Django 3.2.5 on 2022-04-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all_in_one_cp', '0004_delete_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='platform_details',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('Leetcode_username', models.CharField(max_length=200)),
                ('Codeforces_username', models.CharField(max_length=200)),
                ('SPOJ_username', models.CharField(max_length=200)),
                ('Interviewbit_username', models.CharField(max_length=200)),
                ('Atcoder_username', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
