# Generated by Django 3.2.5 on 2022-04-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_in_one_cp', '0005_platform_details_user_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='email',
            field=models.EmailField(default='NA', max_length=254, unique=True),
        ),
    ]
